---
- import_playbook: install_shared.yml
- import_playbook: update_all.yml
- import_playbook: install_db.yml
- import_playbook: install_mp.yml
- import_playbook: install_wb.yml
- import_playbook: install_lb.yml
